#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import sys


REGISTRY_DESCRIPTION = (
    "Private aic registry for skills, contexts, MCP servers, permissions, and local ignore rules."
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate aic-skills registry indexes.")
    parser.add_argument("--repo-root", default=".", help="repository root path")
    parser.add_argument("--registry-version", default="v0.1.0", help="registry version")
    parser.add_argument(
        "--metadata-only",
        action="store_true",
        help="only update VERSION-driven registry metadata",
    )
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    version = args.registry_version.strip()
    if not version:
        raise SystemExit("registry version cannot be empty")
    if not (root / "aic-release.yaml").is_file():
        raise SystemExit("missing aic-release.yaml")

    write_registry_metadata(root, version)
    if args.metadata_only:
        return 0

    write_frontmatter_index(root, version, "skills", "SKILL.md", "skills")
    write_frontmatter_index(root, version, "contexts", "CONTEXT.md", "contexts")
    write_frontmatter_index(
        root, version, "mcp-servers", "MCP-SERVER.md", "mcp_servers"
    )
    write_frontmatter_index(root, version, "permissions", "PERMISSION.md", "permissions")
    write_gitignore_index(root, version)
    return 0


def write_registry_metadata(root: Path, version: str) -> None:
    content = "\n".join(
        [
            f"name: {q('aic-skills')}",
            f"version: {q(version)}",
            f"aic_release: {q('aic-release.yaml')}",
            f"schema: {q('v1')}",
            f"description: {q(REGISTRY_DESCRIPTION)}",
            "",
        ]
    )
    (root / "registry.yaml").write_text(content, encoding="utf-8")


def write_frontmatter_index(
    root: Path, version: str, dir_name: str, marker: str, list_key: str
) -> None:
    entries = collect_frontmatter_entries(root / dir_name, root, marker)
    doc = ["# Code generated by aic-skills/scripts/indexgen. DO NOT EDIT."]
    doc.append(f"registry_version: {q(version)}")
    doc.append(f"{list_key}:")
    if entries:
        for item in entries:
            emit_entry(doc, item)
    else:
        doc.append("    []")
    write_text(root / dir_name / "index.yaml", "\n".join(doc) + "\n")


def write_gitignore_index(root: Path, version: str) -> None:
    gitignore_path = root / "gitignore" / "base" / "gitignore.txt"
    if not gitignore_path.is_file():
        raise SystemExit(f"missing {gitignore_path}")
    doc = [
        "# Code generated by aic-skills/scripts/indexgen. DO NOT EDIT.",
        f"registry_version: {q(version)}",
        "gitignore:",
    ]
    emit_entry(
        doc,
        {
            "name": "base",
            "version": "1.0.0",
            "description": "Default aic project .gitignore entries.",
            "path": "gitignore/base/gitignore.txt",
            "tags": [],
        },
    )
    write_text(root / "gitignore" / "index.yaml", "\n".join(doc) + "\n")


def collect_frontmatter_entries(root: Path, repo_root: Path, marker: str) -> list[dict]:
    if not root.exists():
        return []

    entries: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for path in sorted(root.rglob(marker)):
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        meta = parse_frontmatter(path)
        rel = path.parent.relative_to(repo_root).as_posix()
        item = {
            "name": meta.get("name", "").strip(),
            "version": meta.get("version", "").strip(),
            "description": normalize_text(meta.get("description", "")),
            "tags": sorted(set(meta.get("tags", [])), key=str.lower),
            "path": rel,
        }
        if not item["name"] or not item["version"] or not item["description"]:
            raise SystemExit(f"metadata incomplete in {path}")
        key = (item["name"].lower(), item["version"].lower())
        if key in seen:
            continue
        seen.add(key)
        entries.append(item)

    entries.sort(key=lambda x: (x["name"].lower(), x["version"].lower()))
    return entries


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"{path} missing YAML frontmatter")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration as exc:
        raise SystemExit(f"{path} missing frontmatter terminator") from exc

    meta: dict[str, object] = {}
    i = 1
    while i < end:
        line = lines[i]
        stripped = line.strip()
        i += 1
        if not stripped or stripped.startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            continue
        if ":" not in stripped:
            continue
        key, raw_value = stripped.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value in {">", ">-", "|", "|-"}:
            block = []
            while i < end and (lines[i].startswith(" ") or lines[i].startswith("\t")):
                block.append(lines[i].strip())
                i += 1
            meta[key] = " ".join(part for part in block if part)
            continue
        if key == "tags" and raw_value == "":
            tags = []
            while i < end and lines[i].lstrip().startswith("- "):
                tags.append(unquote(lines[i].lstrip()[2:].strip()))
                i += 1
            meta[key] = tags
            continue
        if key == "tags" and raw_value.startswith("[") and raw_value.endswith("]"):
            body = raw_value[1:-1].strip()
            meta[key] = [unquote(part.strip()) for part in body.split(",") if part.strip()]
            continue
        meta[key] = unquote(raw_value)
    if "tags" not in meta:
        meta["tags"] = []
    return meta


def emit_entry(doc: list[str], item: dict) -> None:
    doc.append(f"    - name: {q(item['name'])}")
    doc.append(f"      version: {q(item['version'])}")
    doc.append(f"      description: {q(item['description'])}")
    tags = item.get("tags", [])
    if tags:
        doc.append("      tags:")
        for tag in tags:
            doc.append(f"        - {q(tag)}")
    doc.append(f"      path: {q(item['path'])}")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"generated {path}")


def normalize_text(value: str) -> str:
    return " ".join(value.strip().split())


def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


if __name__ == "__main__":
    sys.exit(main())
